In [1]:
!pip install plotly

import pandas as pd
import plotly.express as px

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)

In [2]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# Tambah kolom IsAlone
df['IsAlone'] = (df['SibSp'] + df['Parch'] == 0)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsAlone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,True

In [4]:
fig1 = px.histogram(
    df, x="Sex", color="Survived",
    barmode="group",
    title="Survival berdasarkan Gender"
)
fig1.show()

In [5]:
fig2 = px.histogram(
    df, x="Pclass", color="Survived",
    barmode="group",
    title="Survival berdasarkan Pclass"
)
fig2.show()

In [6]:
fig3 = px.histogram(
    df, x="Age", color="Survived",
    title="Distribusi Age terhadap Survival"
)
fig3.show()

In [7]:
fig4 = px.histogram(
    df, x="IsAlone", color="Survived",
    barmode="group",
    title="Survival berdasarkan IsAlone"
)
fig4.show()

Insight:

1. Siapa yang paling berpeluang selamat?
- Perempuan memiliki peluang selamat lebih tinggi dibanding laki-laki
- Penumpang kelas 1 (Pclass = 1) memiliki tingkat survival tertinggi

2. Faktor yang paling berpengaruh:
- Gender (faktor paling dominan)
- Pclass (kelas tiket)
- Fare (harga tiket)
- Usia (anak-anak lebih diutamakan)

In [8]:
df['Fare_group'] = pd.qcut(df['Fare'], 3, labels=['Low Fare', 'Medium Fare', 'High Fare'])

In [9]:
df_filtered = df[df['Age'] < 30]

In [10]:
fig5 = px.scatter(
    df_filtered,
    x="Age",
    y="Fare",
    color="Survived",
    facet_col="Fare_group",
    hover_data=["Sex", "Pclass"],
    title="Scatter Plot Age vs Fare (Age < 30)"
)

fig5.show()

Insight Scatter Plot:

- Penumpang muda (Age < 30) dengan fare tinggi cenderung lebih banyak yang selamat
- Penumpang dengan fare rendah memiliki tingkat survival lebih rendah
- Perempuan tetap dominan selamat di semua kategori
- Kelas atas (Pclass 1) lebih banyak muncul di fare tinggi dan survival tinggi

Fitur interaktif yang digunakan:
- Zooming: pengguna bisa memperbesar grafik
- Hovering: menampilkan detail (Sex, Pclass, dll)
- Filtering visual: melalui legend (klik Survived)
- Facet: membagi grafik berdasarkan Fare_group

In [11]:
fig1.update_layout(template="plotly_dark")
fig2.update_layout(template="plotly_dark")
fig3.update_layout(template="plotly_dark")
fig4.update_layout(template="plotly_dark")
fig5.update_layout(template="plotly_dark")